sudo: required
services:
  - docker

before_install:
  - docker build -t mnuxox/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mnuxox/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-404993142766"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
